### ISSUE TITLE
How can I be sure that  Adjust.trackThirdPartySharing will complete before initializing the SDK?

### ISSUE THREAD

**Issue by lore-co** [adjust/flutter_sdk#106]
While speaking with Adjust's staff an issue arose with the suggested Adjust implementation for enabling/disabling third-party data sharing. 
Let's say that, for any reason, the enabling request reaches Adjust Backend at a later moment than the initialization request: we'd be at risk of losing potential user data.

Like the title says I'm in need of being absolutely sure that the above method (which I presume launches an API call like shown [here](https://help.adjust.com/en/article/block-third-party-data) completes.

I'd expect the above method to return a sort of "ok"/"ko" response, in order to initialize the SDK ONLY **afterward**.
Instead, the method doesn't present a return value.

**Comment by uerceg** [comment]
Hi @lore-co,

Indeed, the method does not return any return value (and I also do see the convenience and flexibility which existence of the one would provide), but the way how Adjust SDK is built under the hood is that it's guaranteed that your interaction with `Adjust` API will be processed in order of calling any of the methods.

So for example, if you make a call to `Adjust.trackThirdPartySharing` method prior to making a call to `Adjust.start` method, SDK is in charge of making sure that third party sharing request is communicated first to the backend and only upon getting the response that third party sharing has been processed, SDK would send session request to backend at which time backend will be aware (based on your third party sharing settings) what is that it should do when it comes to data sharing with that session package and any subsequent request.

The way you can check this logic in motion would be to set SDK to sandbox mode and set log level to verbose and observe the SDK logs and `session` package (caused by an initial call to `Adjust.start` method) will be tracked only after `third_party_sharing` package (caused by a call to `Adjust.trackThirdPartySharing` prior to starting SDK) is tracked and processed by our backend.

In case you have any further questions / comments, feel free to ping.

Cheers

**Comment by lore-co** [comment]
> Hi @lore-co,
> 
> Indeed, the method does not return any return value (and I also do see the convenience and flexibility which existence of the one would provide), but the way how Adjust SDK is built under the hood is that it's guaranteed that your interaction with `Adjust` API will be processed in order of calling any of the methods.
> 
> So for example, if you make a call to `Adjust.trackThirdPartySharing` method prior to making a call to `Adjust.start` method, SDK is in charge of making sure that third party sharing request is communicated first to the backend and only upon getting the response that third party sharing has been processed, SDK would send session request to backend at which time backend will be aware (based on your third party sharing settings) what is that it should do when it comes to data sharing with that session package and any subsequent request.
> 
> The way you can check this logic in motion would be to set SDK to sandbox mode and set log level to verbose and observe the SDK logs and `session` package (caused by an initial call to `Adjust.start` method) will be tracked only after `third_party_sharing` package (caused by a call to `Adjust.trackThirdPartySharing` prior to starting SDK) is tracked and processed by our backend.
> 
> In case you have any further questions / comments, feel free to ping.
> 
> Cheers

Hi there,

Thank you for the explanation.

Is there a way to punctually check whether the current user has given their condense to ThirdPartySharing?
Something like, for example, the **getAppTrackingAuthorizationStatus** method?

If not what do you think about the possibility of introducing one as I saw that a S2S API call exists to check it?

Thank you

**Comment by uerceg** [comment]
Well, there's a big question of true meaningfulness of potential OK/NOK callbacks we would provide for tracking third party sharing package. One of the core principles Adjust SDK is built on is that it there should not be data loss in terms of things it needs to track && that everything will be tracked in order of happening. So in our example from above (if you'd make a call to `Adjust.trackThirdPartySharing` before making a call to `Adjust.start` method), our SDK would enqueue `third_party_sharing` and `session` packages in the queue and will be on a mission to send those packages in that order and nothing else can be tracked until those two packages get sent and dequeued in that order (everything tracked afterwards will just be queued behind these two packages). So SDK successfully tracking this package is kinda expected and scenario which is most probable to happen. In case package doesn't get successfully tracked SDK will be retrying sending of this package until it eventually gets tracked by our backend and we get a message that it has been successfully processed. So if you'd have the ability to know for example that sending of this package has failed, not sure what would be the action you would take upon that because internally SDK will continue to retry sending of this package until it eventually tracks it successfully. With this inner SDK behavior in mind, I'd be curious to hear about some use case you have in mind where the existence of the tracking success / failure information would provide you with some valuable information?

There is currently no way for SDK to provide such info because it's built in pretty agnostic way to this particular piece of information. Third party sharing really works in a way that SDK is in charge to properly and with timing picked by the client (pretty much order of API calls to our SDK) deliver this information to backend and from that moment on, backend is set to properly handle any incoming SDK request with respect to third party sharing settings. Reason why method like `getAppTrackingAuthorizationStatus` exists is simply due to the fact that return value of that method is a result of the call to system iOS API because it's an iOS device-level setting which we simply just read and provide back as a return value of that method (vs. third party sharing which is a conceptually a device setting, but stored in our backend, not on the device).

I am not super familiar with s2s API capabilities, but if you can point me out to method you're having in mind, I think it would definitely be something we could check on our end and see how doable that would be to be added to SDK.

**Comment by lore-co** [comment]
> Well, there's a big question of true meaningfulness of potential OK/NOK callbacks we would provide for tracking third party sharing package. One of the core principles Adjust SDK is built on is that it there should not be data loss in terms of things it needs to track && that everything will be tracked in order of happening. So in our example from above (if you'd make a call to `Adjust.trackThirdPartySharing` before making a call to `Adjust.start` method), our SDK would enqueue `third_party_sharing` and `session` packages in the queue and will be on a mission to send those packages in that order and nothing else can be tracked until those two packages get sent and dequeued in that order (everything tracked afterwards will just be queued behind these two packages). So SDK successfully tracking this package is kinda expected and scenario which is most probable to happen. In case package doesn't get successfully tracked SDK will be retrying sending of this package until it eventually gets tracked by our backend and we get a message that it has been successfully processed. So if you'd have the ability to know for example that sending of this package has failed, not sure what would be the action you would take upon that because internally SDK will continue to retry sending of this package until it eventually tracks it successfully. With this inner SDK behavior in mind, I'd be curious to hear about some use case you have in mind where the existence of the tracking success / failure information would provide you with some valuable information?
> 
> There is currently no way for SDK to provide such info because it's built in pretty agnostic way to this particular piece of information. Third party sharing really works in a way that SDK is in charge to properly and with timing picked by the client (pretty much order of API calls to our SDK) deliver this information to backend and from that moment on, backend is set to properly handle any incoming SDK request with respect to third party sharing settings. Reason why method like `getAppTrackingAuthorizationStatus` exists is simply due to the fact that return value of that method is a result of the call to system iOS API because it's an iOS device-level setting which we simply just read and provide back as a return value of that method (vs. third party sharing which is a conceptually a device setting, but stored in our backend, not on the device).
> 
> I am not super familiar with s2s API capabilities, but if you can point me out to method you're having in mind, I think it would definitely be something we could check on our end and see how doable that would be to be added to SDK.

We just want to call  Adjust.start(configAdjust) the exact moment the trackThirdPartySharing API has return a "OK" status.
That's why we need a way to await for the response or, at least, being able to tell if the call was made successfully.

Regarding the S2S it seems I was mistaken, as the only S2S Api you are using is the enable/disable one

**Comment by uerceg** [comment]
That is currently not possible. In order for SDK to send third party sharing setting to the backend, SDK must be initialized. Calling `Adjust.trackThirdPartySharing` before `Adjust.start` would just cause SDK to cache this information and wait for the initialization to pick it up and make sure to process it in a way that third party sharing package gets tracked before install session has been tracked. But SDK will not proceed with install session tracking or sending of anything else to the backend before we get a response from backend that they have successfully processed third party sharing request.

**Comment by lore-co** [comment]
Ok thank you, will close the issue then.
