### ISSUE TITLE
When you switch from a native app to a Flutter app

### ISSUE THREAD

**Issue by Techlabs-jeonhaedong** [adjust/flutter_sdk#110]
I switched the native app that was in operation to the Flutter app. Then I encountered the error "Ignoring event, earlier unique event tracked". To avoid this error, I need to delete the app from the device, but there is no way to delete my app from the customer's device. I can't even forget the device from the console because I don't know AdId. What should I do?

**Comment by uerceg** [comment]
Hi @Techlabs-jeonhaedong,

I understand that you changed the way how you are making your app (from what I understood, you switched from native to Flutter app), but the error you are getting is happening due to the fact that the same app user has attempted to track an event which you marked as a unique in the dashboard more than once.

Is it not expected on your end that users who update the app to the version written in Flutter to trigger that same event which was tracked for them before the update?

**Comment by Techlabs-jeonhaedong** [comment]
oh. now I understand
