### ISSUE TITLE
Deeplink is not working

### ISSUE THREAD

**Issue by ManzzBaria** [adjust/flutter_sdk#12]
Hello,
When I have tried the deep link directly and install app then i am able to receive deeplink, but when same deeplink put on facebook campaign, then i am not able to receive deeplink on app.

Can you please help me here?

**Comment by uerceg** [comment]
Hi @ManzzBaria 

Not sure I fully understood how your test looked like. Are you saying that you tried to click on tracker URL with deep link parameter inside, install an app afterwards and then upon app opening you have received that link (which is deferred deep linking scenario) but if you tried the same test with FB tracker URL, you haven't? (same question goes for https://github.com/adjust/unity_sdk/issues/160 which seems exactly the same)

How do the tracker URLs you're testing with look like (feel free to replace sensitive information from the URL with some dummy data)?

Cheers

**Comment by ManzzBaria** [comment]
Hello,
Here is my Deeplink which is working fine when I am installing app by clicking on Below link:
https://app.adjust.com/2h70ry7?deeplink=waktiflutter%3A%2F%2Fadjutapk%3FOpenP%3DBsEx%26campaignId%3D%26loadB%3Dd13iw4le2lzlul.cloudfront.net%2Findex.html%26serviceId%3D1156%26M%3Dt%26logs%3Dtrue%26src%3Dadj

But when I am  trying to put following deeplink on Facebook campgain then i am not able to recieve deeplink on App:

waktiflutter://adjutapk?OpenP=BsEx&campaignId=&loadB=d13iw4le2lzlul.cloudfront.net/index.html&serviceId=1156&M=t&logs=true&src=adj


Same things are working fine on pure native android apps and ios apps, but not working only for flutter and Unity3D android and ios apps.

Waiting for positive response.

**Comment by uerceg** [comment]
Do you have your app already installed when you're clicking on these links (meaning you are expecting app to be opened after the click and to get content of the link in the app)?

**Comment by ManzzBaria** [comment]
No, App is not installed, when we click on deeplink it will redirecting me on store and from there i am installing app and opening and checking deeplink but seems its not receiving.

**Comment by uerceg** [comment]
Scheme based link (your 2nd one) is not supposed to work in scenario you are trying it in. That kind of link, once clicked onto, will cause OS to try to open app which handles given scheme name. If app is installed on the device, it will try to open it. If app is not installed, then nothing. You will not be redirected to the store if app is not installed and if you install an app after that, OS is not gonna deliver content of that link in your app upon initial launch.

**Comment by ManzzBaria** [comment]
deferred deeplinking is working when testing directly with this deeplink :
https://app.adjust.com/2h70ry7?deeplink=waktiplay%3A%2F%2Fadjutapk%3FOpenP%3DBsEx%26campaignId%3D%26loadB%3Dd13iw4le2lzlul.cloudfront.net%2Findex.html%26serviceId%3D1156%26M%3Dt%26logs%3Dtrue%26src%3Dadj

then when we try from facebook ad with the below deeplink, the app doesn't receive the deferred deeplink:
waktiplay://adjutapk?OpenP=BsEx&campaignId=&loadB=d13iw4le2lzlul.cloudfront.net/index.html&serviceId=1156&M=t&logs=true&src=adj

Please note that we are working with deferred deeplink through facebook with other java apps and it is working fine.
For flutter we have a problen when trying facebook ads

**Comment by uerceg** [comment]
I see. Might be just the way how deep linking with Facebook works which is not really something we who are replying in SDK repo issues are familiar with. There is one simple fact - if deferred deep linking works well on backend side (Adjust backend and Facebook agreed on attribution and we have received deep link from Facebook which we're gonna send to SDK to report in the app in deferred manner), then SDK should receive deferred deep link and should announce it.

I am not sure what might be wrong in this particular setup, but it would definitely be worth checking first with account management team if everything works well behind the scenes and if Adjust backend is aware of attribution to which that link also belongs. If that happens and deep link sent back to SDK is not being announced and provided to you, then it becomes SDK issue.

In case you have dedicated account manager, please feel free to write them, reference this issue and try to see if attribution on our end is being properly determined for your tests. In case you don't have an AM, feel free to write to support@adjust.com.

Keep us posted in here how did that investigation go. I will close the issues (Unity one as well) until then, but if everything turns out to be fine on backend side and SDK is source of an issue, feel free to reopen issue and we can check what might be wrong.

Looking forward to hear back from you on the issue.

Cheers
