### ISSUE TITLE
deferredDeeplinkCallback not called

### ISSUE THREAD

**Issue by matszafraniec** [adjust/flutter_sdk#124]
Hello,

I have an issue that **deferredDeeplinkCallback** not being called on app startup when I route user from deeplink through Google Play Store (I didn't check AppStore yet). Deeplinks are captured properly when the app is installed.

Here is my codebase:

```
final config = AdjustConfig(
    'myAppToken',
     AdjustEnvironment.production,
  );
  config.logLevel = AdjustLogLevel.verbose;

  config.launchDeferredDeeplink = true;

  config.deferredDeeplinkCallback = (uri) {
    print('[Adjust]: Received deferred deeplink: ' + uri.toString());
  };

  Adjust.start(config);
```

I check it on the released production version to alpha channel in Google Play store.

Adjust_sdk: **4.33.0**
Flutter version: **3.13.6**
Dart version **3.1.3**

**Comment by uerceg** [comment]
Hi @matszafraniec,

In order to see deferred deep link callback being triggered, deep link which was part of your tracker URL you used for testing needs to be sent to the SDK when install gets attributed to click on that tracker URL. For this to be tested you need to:

1. Make sure your tracker URL is properly formatted (it should contain `&deep_link=your-deep-link-content` parameter among other things).
2. In case your tracker URL is made so that it contains device ID of your test device, it should just work. In case you're not using device ID in the tracker URL, then make sure that the tracker from the URL has probabilistic attribution for clicks turned ON.
3. Uninstall your app from your test device.
4. Forget test device from testing console.
5. Click on the tracker URL.
6. Ignore redirection to Play Store and install debug build of your app on your test device.
7. Launch SDK.

After this, install should be tracked and attributed to the click you just did, which should cause deferred deep link info to arrive to the SDK and SDK should ping your callback. You can also set SDK environment to sandbox and log level to verbose and obtain Adjust SDK logs for this test run - they can be helpful to see in case it still doesn't work for you after these steps.

**Comment by matszafraniec** [comment]
Hello @uerceg . I'm in touch with Adjust support.
