### ISSUE TITLE
App-tracking authorisation wrappe not working

### ISSUE THREAD

**Issue by darkobacic-puc** [adjust/flutter_sdk#136]
Hi,

I just found out that the `Adjust.requestTrackingAuthorizationWithCompletionHandler()` isn't working as expected and also not as documented by you. 

**Expected behavior:**
The callback is triggered once the user clicks the "Allow" or "Ask App Not to Track" buttons on the iOS native popup for tracking.

**Actual behavior:**
The callback is triggered immediately (even before the prompt shows) and returns the status **Denied**. And once the user clicks Allow or Deny the callback is not called again.

Also, using the `attConsentWaitingInterval` property didn't affect the behavior.

You can check out the video below to see how it works, I created a new empty project and added the sdk.

**Environments:**
Flutter: 3.19.6
Dart: 3.3.4
Macbook Air M1
Real iPhone 11 - OS17.4 and simulator on 17.4

adjust_sdk: 4.38.1, 4.38.0, 4.36.0, 4.30.0 (just to make sure there's no problem in the latest version).

https://github.com/adjust/flutter_sdk/assets/168414014/e8edf32d-d00a-4593-a3e8-0ac734ef580f

**Comment by matteocoletta** [comment]
Hello @darkobacic-puc, given that your device is running iOS 17.4,the problem looks related to this known bug: https://forums.developer.apple.com/forums/thread/746432

Could you please try to repeat the test after updating the device to the latest iOS version? If the problem persists, please reach out to support@adjust.com so that we can investigate further.
