### ISSUE TITLE
Not able to get info from attributionCallback in iOS side

### ISSUE THREAD

**Issue by Yennefer** [adjust/flutter_sdk#38]
Hello,

I'm trying to receive additional info from the tracker link (namely `campaign` and `clickLabel`) in `adjustConfig.attributionCallback` in our Flutter mobile app. I have achieved this on the Android side, but I'm not getting any data in the iOS app after opening and downloading it from AppStore with adjust tracker link (the link is the same as for the Android app).
If I understood correctly from your Flutter documentation, I don't need to set up any additional settings on the native iOS side of the app to make it work. Please, correct me if I'm wrong.
What can the problem be with my iOS app, which is not allowing me to collect additional info in attribution callback?
Should I add some of the following frameworks from this list to make it work https://github.com/adjust/flutter_sdk#ios-link-additional-frameworks?

My Flutter code is:
```
AdjustConfig config = new AdjustConfig(ADJUST_APP_TOKEN, ADJUST_ENVIRONMENT);
config.logLevel = AdjustLogLevel.debug;
config.attributionCallback = (AdjustAttribution attributionChangedData) {
    if (attributionChangedData.campaign != null) {
        StorageService.setString(TRACKER_CAMPAIGN_KEY, attributionChangedData.campaign);
    }
    if (attributionChangedData.clickLabel != null) {
        StorageService.setString(TRACKER_LABEL_KEY, attributionChangedData.clickLabel);
    }
};
Adjust.start(config);
```

**Comment by uerceg** [comment]
Hi @Yennefer 

Your understanding is correct, there's nothing which you need to additionally set in your app in order to get info inside of the attribution callback.

I would need some additional information on how does your test setup looks like and what are you getting as a result. Would be good if you can provide me:
- How does the tracking link you're using for testing look like (feel free to omit any sensitive information from it)?
- In case you're not having device ID being part of your tracker URL, do you have click fingerprinting enabled for that tracker in the dashboard?
- Are you uninstalling + forgetting the device from Adjust test console before doing the test?
- If all from the above are 👍, can you send us over the SDK verbose logs (set SDK to sandbox mode + set log level to verbose) from test run (again, feel free to omit any sensitive information which might appear in the logs)?

Cheers

**Comment by Yennefer** [comment]
Thank you, @uerceg 

Enabling the fingerprint for the tracker fixed the issue
