### ISSUE TITLE
Flutter ios build error

### ISSUE THREAD

**Issue by umerjavaidkh** [adjust/flutter_sdk#71]
**...../ios/Pods/Adjust/Adjust/Adjust.m:274:16: error: implicit conversion of 'NSURLRequestAttribution' (aka 'enum NSURLRequestAttribution') to 'ADJAttribution * _Nullable' is disallowed with ARC
            return [[Adjust getInstance] attribution];
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...../ios/Pods/Adjust/Adjust/Adjust.m:274:16: warning: incompatible integer to pointer conversion returning 'NSURLRequestAttribution' (aka 'enum NSURLRequestAttribution') from a function with result type 'ADJAttribution * _Nullable' [-Wint-conversion]
            return [[Adjust getInstance] attribution];**

suddenly getting this error during the project build process.
using  adjust_sdk:   4.23.3 to 4.28.0 

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (11 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Comment by uerceg** [comment]
Hi @umerjavaidkh 

Seems to me that you are sticking with older Flutter SDK version(s) because you are still using Flutter 1.x.y, but that you have also updated Xcode version to 13. If that's the case, latest Flutter SDK contains fixes for Xcode 13, but it would force you to upgrade to Flutter 2.x.y. Only workaround I can see is to stick with Xcode 12 until you decide to upgrade Flutter version.
