### ISSUE TITLE
Events are not tracked when is from DeepLink

### ISSUE THREAD

**Issue by felipebastoss** [adjust/flutter_sdk#90]
I'm trying to use Adjust Deeplinks to redirect the user to my app and after all configuration, that's working fine.
But, after the user being redirect to app, the events that are already setted do not appear linked to any tracker on the Dashboard.

Any ideas to solve this?

**Comment by uerceg** [comment]
Hi @felipebastoss,

In those moments when you get redirected to the app, are you tracking event with the Adjust SDK? If yes, does it succeed (you can double check this with SDK being in sandbox mode and log level set to verbose and then simply checking what happens in the SDK logs)? If event tracking works, then you should also see this event with event token you used being tracked in dashboard as well. There might be some delay between tracking the event and appearing in the dashboard, but if you saw in logs that it got tracked, it will appear in dashboard. Another thing which might be worth mentioning is that dashboard is showing production traffic by default, so in case you are running your test from SDK sandbox environment, you'd need to double check sandbox traffic in dashboard to find this event being tracked.

**Comment by felipebastoss** [comment]
Hi @uerceg,

Yep, in those moments the events are being tracked with the Adjust SDK. When the app is openned, the event 'sdk_click', which is default from SDK, is called and appear correctly in the Adjust Dashboard. But the custom events in my app do not appear in the tracker linked to deeplink.

**Comment by uerceg** [comment]
Hi @felipebastoss,

If you set SDK to sandbox mode and log level to verbose, do you see that SDK is tracking those custom events you are trying to look for in dashboard and that backend is responding with event being tracked in the logs?

**Comment by felipebastoss** [comment]
Yep, those events appear in the logs.

**Comment by uerceg** [comment]
Then those should also appear in dashboard. Not immediately after being tracked, there is a bit of delay before they show up in dashboard, but they should be there. In case you're having issues in locating those events in dashboard, I'd advise you to reach out to your dedicated account manager or fire an email to support@adjust.com and you'll be assisted with this topic. I'll close this ticket for now since from SDK point of view everything seems to be working as expected. In case you do have any other questions / doubts, feel free to comment / reopen.
